### ISSUE TITLE
Adding history and project list

### ISSUE THREAD

**Issue by schnuerle** [civicdata/civicdata.github.io#1]
In the new site, is there any chance of adding back in (and updating) some of the history of the CDA?  Eg:  
https://github.com/civicdata/civicdata.github.io-old/blob/167b5c449ce68230a98d174f2afe98d311cbf7c9/about.md

And adding and updating the page that had a list of projects that the CDA was either directly involved in or CDA members worked on or created?  Eg: 
https://github.com/civicdata/civicdata.github.io-old/blob/master/projects.md

I was looking to send this info to some journalists but don't see it on the new site yet.

**Comment by cheapwebmonkey** [comment]
please see https://github.com/civicdata/civicdata.github.io/pull/73
