### ISSUE TITLE
Add back data.civicdataalliance.org

### ISSUE THREAD

**Issue by schnuerle** [civicdata/civicdata.github.io#13]
Just to note to get this back up and running.  On Slack we were looking for the voting precinct shapefiles that were there, and I was looking for the tree canopy data and JCPS resides school shapefiles.

**Comment by thebouv** [comment]
I've had a couple false starts on this using JKAN, but with a block of time I know I can get it sorted out. Hopefully within next couple weeks providing real-life stops kicking me in the face.

**Comment by mgottholsen** [comment]
If you need assistance, let me know @thebouv
