### ISSUE TITLE
Commas in the URLs

### ISSUE THREAD

**Issue by schnuerle** [civicdata/civicdata.github.io#14]
It seems like some URLs have commas in them in odd places, like these: 

http://www.civicdataalliance.org/projects,/hackathons/gis-open-data-american-printing-house-open-street-map/

http://www.civicdataalliance.org/projects,/hackathons/minecraft-louisville/

But not all project urls do, eg: 

http://www.civicdataalliance.org/hackathons/projects/code-across-louisville-2016/

**Comment by jessetylermullins** [comment]
@schnuerle I know this is an old issue but any help pointing out where these broken links are would be helpful in fixing them.

**Comment by cheapwebmonkey** [comment]
The url structure is built with tags, automatically by jekyll

**Comment by schnuerle** [comment]
So is the solution to edit the tags for these posts, and remove errant commas?

In this post: 
https://raw.githubusercontent.com/civicdata/civicdata.github.io/master/_posts/2015-03-04-gis-open-data-american-printing-house-open-street-map.md
http://www.civicdataalliance.org/projects,/hackathons/gis-open-data-american-printing-house-open-street-map/

You can see the metadata line at the top that says 'categories: projects, hackathons'.  Is the ',' showing up in the URL because the space between the categories acts like a comma?

For example, this post has a good URL with 2 categories, but there is no comma between them, only a space. 

https://raw.githubusercontent.com/civicdata/civicdata.github.io/master/_posts/2017-06-18-doc-win-louisville-pat-smith.md
http://www.civicdataalliance.org/projects/blog/doc-win-louisville-pat-smith/

So if this is the case, then the commas just have to be removed from the categories on the posts that have them.
