### ISSUE TITLE
Old URL redirection

### ISSUE THREAD

**Issue by schnuerle** [civicdata/civicdata.github.io#15]
Would it be possible to add URL redirection from the old URLs that used to work, to the corresponding new URL structure, to preserve links from other sites, social media, wikis, etc?  

Eg this:
http://www.civicdataalliance.org/gis-open-data-american-printing-house-open-street-map/

is a 404 but should go to this:
http://www.civicdataalliance.org/projects,/hackathons/gis-open-data-american-printing-house-open-street-map/

**Comment by cheapwebmonkey** [comment]
Please submit a list of the urls on which you'd like a redirect.

**Comment by mgottholsen** [comment]
Added Jeykll layouts for internal and external redirects in this commit - 1991ef3a45ec3230effc02bdb26ece8c69b3944c

Just need to create stubs for redirection.

**Comment by schnuerle** [comment]
Is there a way to get a list of posts/pages from the old site from the repo? That can be the list to redirect to the new pages. This should do it: https://github.com/civicdata/civicdata.github.io-old/tree/master/_posts

**Comment by cheapwebmonkey** [comment]
please ref: https://github.com/civicdata/civicdata.github.io/pull/73
