### ISSUE TITLE
CSS to make text links visible without need to hover

### ISSUE THREAD

**Issue by schnuerle** [civicdata/civicdata.github.io#16]
Add some CSS so you can see links highlighted or underlined in some way, without the need to hover over each work on the page to discover them. 

For example, the "CDA Work before the event" numbered list here has many links throughout, but on desktop you have to mouse-hover to discover that they are there: 
http://www.civicdataalliance.org/projects,/hackathons/gis-open-data-american-printing-house-open-street-map/

**Comment by cheapwebmonkey** [comment]
No underlines, please. Use the branding color palette and sass

**Comment by mgottholsen** [comment]
Three logo colors:

"Civic Teal"
HTML code:	#38C1C9
RGB code:	R: 56 G: 193 B: 201
HSV:	183.31° 72.14% 78.82%

"Civic Red"
HTML code:	#EF1D26
RGB code:	R: 239 G: 29 B: 38
HSV:	357.43° 87.87% 93.73%

"Civic Warm Gray"
HTML code:	#2D2E30
RGB code:	R: 45 G: 46 B: 48
HSV:	220° 6.25% 18.82%

**Comment by mgottholsen** [comment]
Fixed with fe9b0b66644bd8776bb46497d0f178ffe3acbc5d
