### ISSUE TITLE
Create jobs board using API

### ISSUE THREAD

**Issue by bapatrick** [civicdata/civicdata.github.io#18]
Create jobs board for CDA website and integrate to Slack

**Comment by mgottholsen** [comment]
Added a feedjira plugin with 1991ef3a45ec3230effc02bdb26ece8c69b3944c to harvest from a feed. See feedjira docs.

**Comment by cheapwebmonkey** [comment]
could we get a link to the feedjira docs, please

**Comment by mgottholsen** [comment]
http://feedjira.com/
https://github.com/feedjira/feedjira

**Comment by mgottholsen** [comment]
Here is a walkthrough, pulling Medium RSS using Feedjira - https://medium.com/@jameshamann/displaying-medium-posts-on-your-jekyll-website-7eef230309e4
