### ISSUE TITLE
update favicon to new CDA logo

### ISSUE THREAD

**Issue by jessetylermullins** [civicdata/civicdata.github.io#23]

**Comment by mgottholsen** [comment]
Fixed with b87860869460bf4e2080caaad727e3d320c433d7

**Comment by jessetylermullins** [comment]
@mgottholsen favicons have not updated for me on Chrome.

**Comment by jessetylermullins** [comment]
[/_includes/head.html](https://github.com/civicdata/civicdata.github.io/blob/master/_includes/head.html) has many icon links with `?v=new_logo` attached at the end before the closing quote. Removing that in dev tools fixed the filepath and the new logo showed up properly in Chrome.

**Comment by mgottholsen** [comment]
That's strange, the new_logo parameter should have forced it to reload and replace the old one in cache. I wonder if Github's web server doesn't process that...

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jessetylermullins** [comment]
@mgottholsen I created PR #46 to fix the issue - assigned you to review.
