### ISSUE TITLE
add responsive styling and menu for smaller screens

### ISSUE THREAD

**Issue by jessetylermullins** [civicdata/civicdata.github.io#31]

**Comment by mgottholsen** [comment]
I like how BBC handles their menu, it's similar in layout to ours, but on smaller screens, it collapses items into a "More" link.

![image](https://user-images.githubusercontent.com/11966842/34918654-0b053b6c-f924-11e7-93f4-a233e2d63c59.png)

**Comment by cheapwebmonkey** [comment]
interesting- I think it looks better, tho I'm not a fan of putting everything under a more tab. 

Maybe a hamburger menu would be a good compromise, as everyone online knows what those should do? They have an expected user behavior, in other words.

**Comment by jessetylermullins** [comment]
Maybe a combination of 2 - 3 main links like "about" and "calendar" (open to discussion on which) and then a hamburger/3 dots menu icon for the rest? Present the most important links we want people to visit and then hide everything else under something most people understand.
