### ISSUE TITLE
Name Misspelled

### ISSUE THREAD

**Issue by edblayney** [civicdata/civicdata.github.io#38]
**>Ed Blaney** [@edblayney](https://twitter.com/edblayney) - Innovation Project Manager, [Office of Performance Improvement and Innovation](https://louisvilleky.gov/government/performance-improvement-innovation/about-us)

Name should be: Ed Blayney

NOTE: this may be the first issue I have ever opened, and I am only doing it cause I am trying to learn more about GitHub. Really don't care about my name being misspelled.

**Comment by cheapwebmonkey** [comment]
Should be ok now: http://www.civicdataalliance.org/about/
