### ISSUE TITLE
replace CoC link on "About" page with updated CDA CoC link

### ISSUE THREAD

**Issue by jessetylermullins** [civicdata/civicdata.github.io#44]
Updated CoC can be found here: https://github.com/civicdata/civicdata.github.io/blob/master/CODE_OF_CONDUCT.md

**Comment by mgottholsen** [comment]
This would be a use case for the "Jekyll per repo" idea. JSON feed from docs site would automatically update the cda main site.

**Comment by jessetylermullins** [comment]
I like the idea - I just wonder if we have the available labor to maintain it properly at this point. Plus an issue like this is a good, easy task to offer up for Code Louisville students or new CDA members who want to contribute.

**Comment by mgottholsen** [comment]
See https://github.com/civicdata/civicdata.github.io/issues/45

**Comment by cheapwebmonkey** [comment]
Who is responsible for mainting the added Json feeds? 

I’d personally prefer just updating the markdown without the added hoop/burden of feed maintenance.

I’m having a hard time not seeing this as unnecessary tech debt.

Convince me otherwise

**Comment by mgottholsen** [comment]
The JSON would automatically update when the markdown was updated on the repo, because it would use a Jekyll json layout.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by cheapwebmonkey** [comment]
I'm still unclear as to how this would be implemented- maybe as here? https://stevenwestmoreland.com/2017/05/adding-json-feed-to-your-jekyll-site.html

**Comment by jessetylermullins** [comment]
PR #47 fixes this issue.

**Comment by jessetylermullins** [comment]
PR #47 was merged so this issue is resolved.

Please see #45 for continued discussion on the "Jekyll per repo" idea.
