### ISSUE TITLE
Logo link on internal pages takes you typeform?

### ISSUE THREAD

**Issue by jessetylermullins** [civicdata/civicdata.github.io#48]
I think expected user behavior would be to click on the logo/name and it take you to the homepage. I was surprised when it took me to the typeform.

**Comment by jessetylermullins** [comment]
Maybe a `Join` link in the main nav as well as the icon in the header would suffice for membership signups?

**Comment by mgottholsen** [comment]
Yeah, that was an artifact of updating the logo, and reusing it in the header. I need to break out that portion of the Jekyll layout.

**Comment by mgottholsen** [comment]
Fixed with 6c94b405ba1480d19261cebbafa2fe9ae6abcfe6
