### ISSUE TITLE
jsonfeed.html YAML doesn't work

### ISSUE THREAD

**Issue by mgottholsen** [civicdata/civicdata.github.io#50]
I put the jsonfeed.html YAML file in place as a starting point to generate a jsonfeed spec .json file. It currently does not work, and need to be fixed.

**Comment by cheapwebmonkey** [comment]
what branch did this happen in?

**Comment by thebouv** [comment]
Started looking back to see where this was introduced into master and deployed.  Think we got ahead of ourselves with that and it shouldn't have made it up into a merge.

I see we have a placeholder for Contributing.md now so I'm going to take a stab at writing up an explanation of our chosen workflow (which is basically github flow).  Likely I'll work on moving around some permissions as well to streamline how we handle merges.

Before I get to that though I'm going to look at this bug specifically, try to revert the commits that caused it, and then move forward with the other things mentioned above.

**Comment by mgottholsen** [comment]
Yeah, this was my fault, although I think it would be just as much effort to remove it as to getting it operational.

**Comment by mgottholsen** [comment]
See 1cf566ad877dd484637ea8a23c1487db2fbbd0d6

Output:
![image](https://user-images.githubusercontent.com/11966842/35047708-c11cb34e-fb68-11e7-8b19-8827eebf749e.png)
