### ISSUE TITLE
Event Request Form

### ISSUE THREAD

**Issue by bapatrick** [civicdata/civicdata.github.io#52]
Create a form for orgs/company to request hosting an event with us, such as a hackathon.

**Comment by mgottholsen** [comment]
Do you have a preference on if it should be a Typeform, or standard HTML email form. Also, what sort of information would you like to ask for on the form?

**Comment by bapatrick** [comment]
I would just use what I've put on the google form for now as a guide. I'm fine with either way, so whatever you think is best in terms of form style/concept.

**Comment by cheapwebmonkey** [comment]
I think typeform is fine until we start hitting the free 100 entries per month cap, then we will need to pay for the service or use something else. 

Here is an open source alternative to typeform. I have not used this, so cannot comment on integrations, etc. Basically putting this here for ref https://github.com/tellform/tellform

@bapatrick can you add a link to the events google doc please?
